nav:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'getting-started/'
  - 'GitOps Fundamentals': 'gitops-fundamentals/'
  - 'Crossplane Fundamentals': 'crossplane-fundamentals/'
  - 'Crossplane Advanced Patterns': 'crossplane-advanced-patterns/'
  # - 'Security': 'security/'
  # - 'Observability': 'observability/'
  - 'Repository Management': 'repository-management/'
  # - 'Advanced Topics': 'advanced/'
  # - 'Troubleshooting': 'troubleshooting.md'

flatten_single_child_sections: true 